name: Bundle Web Assets

on:
    push:
        paths:
            - "frontend/**"
            - "frontend-bundler/**"
            - ".github/workflows/Bundle.yml"
        branches:
            - bundled
            - main
            - bundle-with-more-clearity
    workflow_dispatch:

jobs:
    trigger:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Git Config
              run: |
                  git config --global user.email "github-action@users.noreply.github.com"
                  git config --global user.name "GitHub Action"
            # Ignore the build changes from previous run.
            # This "just" hard resets to the latest commit on main.
            # The previous bundle commit will still exist, but will be "dangling", unless we made a tag for it.
            # Github will eventually clean dangling commits, which is fine because again, the ones with a tag will stay around.
            - name: Make Sure Release Is Reset To Main
              run: |
                  git checkout -b release-with-more-clearity
                  git reset --hard $GITHUB_SHA
            # Do the actual bundling
            - uses: actions/setup-node@v2
              with:
                  node-version: 17.x
                  cache: "npm"
                  cache-dependency-path: frontend-bundler/package-lock.json
            - run: npm install
              working-directory: frontend-bundler
            - name: The Actual Build
              working-directory: frontend-bundler
              run: npm run build
            # Push the new changes
            - name: Force push frontend-dist changes
              run: |
                  git add frontend-dist --force
                  git commit -m "Parcel Bundle"
                  git push origin release
