name: Trigger release on https://github.com/fonsp/pluto-on-binder

on:
  release:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/fonsp/pluto-on-binder/dispatches \
            -d '{"event_type":"hello friend"}'
